### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by lagosnomad** [sham00n/buster#12]
Hi, I get a Type error while trying to generate a company email and returns info associated with it using the command `buster -f john -l doe -c company.com`

Below is the stack trace and a screenshot is also attached

l4sec:buster mac$ buster -f john -l doe -c company.com
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 11, in <module>
    load_entry_point('buster==1.0.0', 'console_scripts', 'buster')()
  File "/usr/local/lib/python3.7/site-packages/buster-1.0.0-py3.7.egg/buster/lib/run.py", line 177, in start
    email_info=gen_work_email(args.first,args.last,args.company,api_key)
  File "/usr/local/lib/python3.7/site-packages/buster-1.0.0-py3.7.egg/buster/lib/gen_work_email.py", line 52, in gen_work_email
    work_email_info["twitter"]="https://www.twitter.com/" + data["data"]["twitter"]
TypeError: can only concatenate str (not "NoneType") to str

![image](https://user-images.githubusercontent.com/8760121/82603708-0c855900-9bab-11ea-964e-0e3e7c02639e.png)

**Comment by jrizz922** [comment]
Similar issue here:

we couldnt find any email that matches the pattern you provided,try adding more info with the -a option
Traceback (most recent call last):
  File "/opt/homebrew/bin/buster", line 33, in <module>
    sys.exit(load_entry_point('buster==1.0.0', 'console_scripts', 'buster')())
  File "/opt/homebrew/lib/python3.9/site-packages/buster-1.0.0-py3.9.egg/buster/lib/run.py", line 152, in start
    print("[=]Validating " + str(len(generated_emails)) + " possible emails")
TypeError: object of type 'NoneType' has no len()
