### ISSUE TITLE
can't install the buster

### ISSUE THREAD

**Issue by jeremycooper19955** [sham00n/buster#14]
hi,
when I type python3 setup.py install for some reason nothing happends (even though i have python 3)
* I am currently using cmd to run it
and when I type python setup.py install I'm getting the following error:

Compiling src/gevent/resolver/cares.pyx because it depends on C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Cython\Includes\libc\string.pxd.
[1/1] Cythonizing src/gevent/resolver/cares.pyx
Compiling src/gevent/libev/corecext.pyx because it depends on C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Cython\Includes\libc\string.pxd.
[1/1] Cythonizing src/gevent/libev/corecext.pyx
warning: no files found matching 'changelog.rst'
warning: no files found matching 'Makefile.ext'
warning: no files found matching 'known_failures.py'
warning: no files found matching '.pep8'
no previously-included directories found matching '*\__pycache__'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.lo' found anywhere in distribution
warning: no previously-included files matching '*.la' found anywhere in distribution
warning: no previously-included files matching '.dirstamp' found anywhere in distribution
warning: no previously-included files matching 'config.log' found anywhere in distribution
warning: no previously-included files matching 'config.status' found anywhere in distribution
warning: no previously-included files matching 'config.cache' found anywhere in distribution
no previously-included directories found matching 'docs\_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.coverage' found under directory 'src\greentest'
no previously-included directories found matching 'src\greentest\htmlcov'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps\c-ares'
warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps\c-ares'
warning: no previously-included files matching '_corecffi.c' found under directory 'src\gevent'
warning: no previously-included files found matching 'configure-output'
warning: no previously-included files found matching 'configure-output.txt'
warning: no previously-included files found matching 'deps\TAGS'
warning: no previously-included files found matching 'deps\c-ares\ares_build.h'
warning: no previously-included files found matching 'deps\c-ares\ares_config.h'
warning: no previously-included files found matching 'deps\c-ares\libcares.pc'
warning: no previously-included files found matching 'deps\c-ares\libtool'
warning: no previously-included files found matching 'deps\c-ares\Makefile'
no previously-included directories found matching 'deps\c-ares\.deps'
no previously-included directories found matching 'deps\c-ares\.libs'
no previously-included directories found matching 'deps\libev\.deps'
no previously-included directories found matching 'deps\libev\.libs'
warning: no previously-included files matching 'Makefile' found under directory 'deps\libev'
warning: no previously-included files matching 'libtool' found under directory 'deps\libev'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps\libev'
warning: no previously-included files matching 'config.h' found under directory 'deps\libev'
no previously-included directories found matching 'deps\libuv\.deps'
no previously-included directories found matching 'deps\libuv\.libs'
no previously-included directories found matching 'deps\libuv\src\.deps'
no previously-included directories found matching 'deps\libuv\src\unix\.deps'
no previously-included directories found matching 'deps\libuv\src\win\.deps'
no previously-included directories found matching 'deps\libuv\test\.deps'
no previously-included directories found matching 'deps\libuv\autom4te.cache'
no previously-included directories found matching 'deps\libuv\m4'
warning: no previously-included files matching 'Makefile' found under directory 'deps\libuv'
warning: no previously-included files matching 'Makefile.in' found under directory 'deps\libuv'
warning: no previously-included files matching 'ar-lib' found under directory 'deps\libuv'
warning: no previously-included files matching 'aclocal.m4' found under directory 'deps\libuv'
warning: no previously-included files matching 'compile' found under directory 'deps\libuv'
warning: no previously-included files matching 'configure' found under directory 'deps\libuv'
warning: no previously-included files matching 'depcomp' found under directory 'deps\libuv'
warning: no previously-included files matching 'install-sh' found under directory 'deps\libuv'
warning: no previously-included files matching 'libtool' found under directory 'deps\libuv'
warning: no previously-included files matching 'libuv.pc' found under directory 'deps\libuv'
warning: no previously-included files matching 'ltmain.sh' found under directory 'deps\libuv'
warning: no previously-included files matching 'missing' found under directory 'deps\libuv'
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
    return self.find_available_vc_vers()[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cffi\setuptools_ext.py", line 142, in run
    base_class.run(self)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\\AppData\Local\Temp\easy_install-j2c1jbeg\gevent-20.6.2\_setuputils.py", line 352, in build_extension
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 327, in compile
    self.initialize()
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 224, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
    return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
    self.si = SystemInfo(self.ri, vc_ver)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
    self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
    raise distutils.errors.DistutilsPlatformError(err)
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\\AppData\Local\Temp\easy_install-j2c1jbeg\gevent-20.6.2\setup.py", line 471, in <module>
  File "C:\Users\\AppData\Local\Temp\easy_install-j2c1jbeg\gevent-20.6.2\setup.py", line 338, in run_setup
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
    raise
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\\AppData\Local\Temp\easy_install-j2c1jbeg\gevent-20.6.2\setup.py", line 471, in <module>
  File "C:\Users\\AppData\Local\Temp\easy_install-j2c1jbeg\gevent-20.6.2\setup.py", line 338, in run_setup
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
    dist = best[req.key] = env.best_match(
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
    return installer(requirement)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

C:\Users\\Python github\buster-master>sudo python3 setup.py install
'sudo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Python github\buster-master>sudo python setup.py install
'sudo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\\Python github\buster-master>python3 -m pip install --upgrade setuptools

C:\Users\\Python github\buster-master>python -m pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-49.2.0-py3-none-any.whl (789 kB)
     |████████████████████████████████| 789 kB 598 kB/s
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed setuptools-49.2.0

C:\Users\\Python github\buster-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 164, in setup
    _install_setup_requires(attrs)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
    dist = best[req.key] = env.best_match(
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
    return installer(requirement)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\installer.py", line 133, in fetch_build_egg
    wheel.install_as_egg(dist_location)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\wheel.py", line 99, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\wheel.py", line 107, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\wheel.py", line 152, in _convert_metadata
    os.rename(dist_info, egg_info)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Python github\\buster-master\\.eggs\\grequests-0.6.0-py3.8.egg\\grequests-0.6.0.dist-info' -> 'C:\\Users\Python github\buster-master\\.eggs\\grequests-0.6.0-py3.8.egg\\EGG-INFO'

**Comment by ghost** [comment]
Use python3 rather than python, as in:
 $ python3 setup.py install
