### ISSUE TITLE
ModuleNotFoundError: No module named 'zope.event'

### ISSUE THREAD

**Issue by royki** [sham00n/buster#20]
Getting errors of `ModuleNotFoundError: No module named 'zope.event'` after installation.

```shell
 buster -h                             
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 33, in <module>
    sys.exit(load_entry_point('buster==1.0.0', 'console_scripts', 'buster')())
  File "/usr/local/bin/buster", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/buster-1.0.0-py3.9.egg/buster/__main__.py", line 2, in <module>
    from .lib.run import start
  File "/usr/local/lib/python3.9/dist-packages/buster-1.0.0-py3.9.egg/buster/lib/run.py", line 1, in <module>
    from .validate_email import validate_email
  File "/usr/local/lib/python3.9/dist-packages/buster-1.0.0-py3.9.egg/buster/lib/validate_email.py", line 1, in <module>
    import grequests
  File "/home/bstr/buster/.eggs/grequests-0.6.0-py3.9.egg/grequests.py", line 22, in <module>
    curious_george.patch_all(thread=False, select=False)
  File "/home/bstr/buster/.eggs/gevent-21.1.2-py3.9-linux-x86_64.egg/gevent/monkey.py", line 1226, in patch_all
    from gevent import events
  File "/home/bstr/buster/.eggs/gevent-21.1.2-py3.9-linux-x86_64.egg/gevent/events.py", line 71, in <module>
    from zope.event import subscribers
ModuleNotFoundError: No module named 'zope.event'
```

**Comment by BashedCode** [comment]
I was getting this too. Need to reinstall the zope.event package in Kali. Something is busted there.

pip3 install --force-reinstall zope.event

**Comment by leptoid** [comment]
> I was getting this too. Need to reinstall the zope.event package in Kali. Something is busted there.
> 
> pip3 install --force-reinstall zope.event

Thanks!  This worked for me!

**Comment by iwtga** [comment]
Thanks @BashedCode
