### ISSUE TITLE
help !!!!

### ISSUE THREAD

**Issue by asdepikarsenik** [sham00n/buster#23]
hi, 
i'll highly appreciate if i get asssistance to fix my issue, 
everytime i try using buster with an email target : buster -e ******@*******.com i''m getting this error message :+1: 

Traceback (most recent call last):
  File "/usr/local/bin/buster", line 33, in <module>
    sys.exit(load_entry_point('buster==1.0.0', 'console_scripts', 'buster')())
  File "/usr/local/lib/python3.9/dist-packages/buster-1.0.0-py3.9.egg/buster/lib/run.py", line 77, in start
    keys = yaml.safe_load(api_keys)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/usr/local/lib/python3.9/dist-packages/buster-1.0.0-py3.9.egg/data/api-keys.yaml", line 2, column 9

**Comment by ghost** [comment]
Did you register with [hunter.io](hunter.io) and get `api` credentials?
