### ISSUE TITLE
Errors during installation.. Please help!

### ISSUE THREAD

**Issue by haarshdev** [sham00n/buster#27]
Hi,

I have tried to install buster in Ubuntu machine through AWS. However, the installation seems to be not working as buster -h command is not found. I have included the output below for your kind consideration. Thanks for the help!

ubuntu@ip-172-31-63-193:~/buster$ sudo python3 setup.py install
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
zip_safe flag not set; analyzing archive contents...

Installed /home/ubuntu/buster/.eggs/twint-2.1.20-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for gevent
Reading https://pypi.org/simple/gevent/
Downloading https://files.pythonhosted.org/packages/6a/d1/076ca399a40b8339c5cf921e13620d17a2faceda4db315d01435a8df7448/gevent-21.1.2-cp38-cp38-manylinux2010_x86_64.whl#sha256=96f704561a9dd9a817c67f2e279e23bfad6166cf95d63d35c501317e17f68bcf
Best match: gevent 21.1.2
Processing gevent-21.1.2-cp38-cp38-manylinux2010_x86_64.whl
Installing gevent-21.1.2-cp38-cp38-manylinux2010_x86_64.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/gevent-21.1.2-py3.8-linux-x86_64.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for grequests
Reading https://pypi.org/simple/grequests/
Downloading https://files.pythonhosted.org/packages/ed/4c/926fe81584bb9139511ec6490a924362dcc49d3d33a7fa20a7dc6515c266/grequests-0.6.0-py3-none-any.whl#sha256=6eff964416021bb1dee4182a56cc2b551bfa42d37820e6aee6f2efa00d43a061
Best match: grequests 0.6.0
Processing grequests-0.6.0-py3-none-any.whl
Installing grequests-0.6.0-py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/grequests-0.6.0-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for lxml
Reading https://pypi.org/simple/lxml/
Downloading https://files.pythonhosted.org/packages/e5/d7/2d8b9e1d4fe05b8b72b3d2345d5a741b005640681482502b5ce3d8f020d4/lxml-4.6.3-cp38-cp38-manylinux1_x86_64.whl#sha256=26e761ab5b07adf5f555ee82fb4bfc35bf93750499c6c7614bd64d12aaa67927
Best match: lxml 4.6.3
Processing lxml-4.6.3-cp38-cp38-manylinux1_x86_64.whl
Installing lxml-4.6.3-cp38-cp38-manylinux1_x86_64.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/lxml-4.6.3-py3.8-linux-x86_64.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for beautifulsoup4
Reading https://pypi.org/simple/beautifulsoup4/
Downloading https://files.pythonhosted.org/packages/d1/41/e6495bd7d3781cee623ce23ea6ac73282a373088fcd0ddc809a047b18eae/beautifulsoup4-4.9.3-py3-none-any.whl#sha256=fff47e031e34ec82bf17e00da8f592fe7de69aeea38be00523c04623c04fb666
Best match: beautifulsoup4 4.9.3
Processing beautifulsoup4-4.9.3-py3-none-any.whl
Installing beautifulsoup4-4.9.3-py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/beautifulsoup4-4.9.3-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for cython
Reading https://pypi.org/simple/cython/
Downloading https://files.pythonhosted.org/packages/a4/3e/e19fed37a5fa06c62c796bf46c806d1aae83b2e03ba453830153b12885c0/Cython-3.0a6-cp38-cp38-manylinux1_x86_64.whl#sha256=8cfc5738a09eab0b59b8309e6a38152eefcf14e4fc2a02edb772c4ab7226af3b
Best match: Cython 3.0a6
Processing Cython-3.0a6-cp38-cp38-manylinux1_x86_64.whl
Installing Cython-3.0a6-cp38-cp38-manylinux1_x86_64.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/Cython-3.0a6-py3.8-linux-x86_64.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for schedule
Reading https://pypi.org/simple/schedule/
Downloading https://files.pythonhosted.org/packages/eb/3b/040bd180eaef427dd160562ee66adc9f4f67088185c272edcdb899c609c7/schedule-1.1.0-py2.py3-none-any.whl#sha256=617adce8b4bf38c360b781297d59918fbebfb2878f1671d189f4f4af5d0567a4
Best match: schedule 1.1.0
Processing schedule-1.1.0-py2.py3-none-any.whl
Installing schedule-1.1.0-py2.py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/schedule-1.1.0-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for pysocks
Reading https://pypi.org/simple/pysocks/
Downloading https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl#sha256=2725bd0a9925919b9b51739eea5f9e2bae91e83288108a9ad338b2e3a4435ee5
Best match: PySocks 1.7.1
Processing PySocks-1.7.1-py3-none-any.whl
Installing PySocks-1.7.1-py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/PySocks-1.7.1-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for pandas
Reading https://pypi.org/simple/pandas/
Downloading https://files.pythonhosted.org/packages/c8/3b/50dd12d901d5ec760d5ee169dfcb4917f73caa200e19c5da9623b62f2cea/pandas-1.2.4-cp38-cp38-manylinux1_x86_64.whl#sha256=971e2a414fce20cc5331fe791153513d076814d30a60cd7348466943e6e909e4
Best match: pandas 1.2.4
Processing pandas-1.2.4-cp38-cp38-manylinux1_x86_64.whl
Installing pandas-1.2.4-cp38-cp38-manylinux1_x86_64.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/pandas-1.2.4-py3.8-linux-x86_64.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for googletransx
Reading https://pypi.org/simple/googletransx/
Downloading https://files.pythonhosted.org/packages/27/e1/77cd530afec7944d40c5bdd260bcc111be4012b045c82d4e3ffec90b2a42/googletransx-2.4.2.tar.gz#sha256=c46567e3365c2abbe8af1004121b6303f530bf72025d1c3045ed14861902d6da
Best match: googletransx 2.4.2
Processing googletransx-2.4.2.tar.gz
Writing /tmp/easy_install-gl59ib_v/googletransx-2.4.2/setup.cfg
Running googletransx-2.4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gl59ib_v/googletransx-2.4.2/egg-dist-tmp-vm3xb4wy
zip_safe flag not set; analyzing archive contents...
Moving googletransx-2.4.2-py3.8.egg to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/googletransx-2.4.2-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for geopy
Reading https://pypi.org/simple/geopy/
Downloading https://files.pythonhosted.org/packages/0c/67/915668d0e286caa21a1da82a85ffe3d20528ec7212777b43ccd027d94023/geopy-2.1.0-py3-none-any.whl#sha256=4db8a2b79a2b3358a7d020ea195be639251a831a1b429c0d1b20c9f00c67c788
Best match: geopy 2.1.0
Processing geopy-2.1.0-py3-none-any.whl
Installing geopy-2.1.0-py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/geopy-2.1.0-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for fake-useragent
Reading https://pypi.org/simple/fake-useragent/
Downloading https://files.pythonhosted.org/packages/d1/79/af647635d6968e2deb57a208d309f6069d31cb138066d7e821e575112a80/fake-useragent-0.1.11.tar.gz#sha256=c104998b750eb097eefc28ae28e92d66397598d2cf41a31aa45d5559ef1adf35
Best match: fake-useragent 0.1.11
Processing fake-useragent-0.1.11.tar.gz
Writing /tmp/easy_install-j5it13em/fake-useragent-0.1.11/setup.cfg
Running fake-useragent-0.1.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-j5it13em/fake-useragent-0.1.11/egg-dist-tmp-rv0rprwt
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
creating /home/ubuntu/buster/.eggs/fake_useragent-0.1.11-py3.8.egg
Extracting fake_useragent-0.1.11-py3.8.egg to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/fake_useragent-0.1.11-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for elasticsearch
Reading https://pypi.org/simple/elasticsearch/
Downloading https://files.pythonhosted.org/packages/09/93/461a042becf2a35a666fb7dbb2fa31f0f766dfd1b01e7d971f4ad51f0d69/elasticsearch-7.12.0-py2.py3-none-any.whl#sha256=c67b0f6541eda6de9f92eaea319c070aa2710c5d4d4ee5e3dfa3c21bd95aa378
Best match: elasticsearch 7.12.0
Processing elasticsearch-7.12.0-py2.py3-none-any.whl
Installing elasticsearch-7.12.0-py2.py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/elasticsearch-7.12.0-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for cchardet
Reading https://pypi.org/simple/cchardet/
Downloading https://files.pythonhosted.org/packages/c8/e3/11ead63869139948f61b922a1539f4439554358e6b4d304ccf2f1c836004/cchardet-2.1.7-cp38-cp38-manylinux1_x86_64.whl#sha256=90086e5645f8a1801350f4cc6cb5d5bf12d3fa943811bb08667744ec1ecc9ccd
Best match: cchardet 2.1.7
Processing cchardet-2.1.7-cp38-cp38-manylinux1_x86_64.whl
Installing cchardet-2.1.7-cp38-cp38-manylinux1_x86_64.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/cchardet-2.1.7-py3.8-linux-x86_64.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for aiohttp_socks
Reading https://pypi.org/simple/aiohttp_socks/
Downloading https://files.pythonhosted.org/packages/9a/6c/d302e5a8097fee1e83b9f8e9da10d7752fbf27c74db18b3cc9528b3479be/aiohttp_socks-0.6.0-py3-none-any.whl#sha256=db7aa48c0758ee45d7dbc1fde499912ec6fb77eab77a6e2808825d1f41d4e300
Best match: aiohttp-socks 0.6.0
Processing aiohttp_socks-0.6.0-py3-none-any.whl
Installing aiohttp_socks-0.6.0-py3-none-any.whl to /home/ubuntu/buster/.eggs

Installed /home/ubuntu/buster/.eggs/aiohttp_socks-0.6.0-py3.8.egg
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Searching for aiohttp
Reading https://pypi.org/simple/aiohttp/
Downloading https://files.pythonhosted.org/packages/f0/f2/703dba52c7620199ea0ec8ea9a4a2f06203b4893b94f60240c2c10225043/aiohttp-4.0.0a1.tar.gz#sha256=b5036133c1ba77ed5a70208d2a021a90b76fdf8bf523ae33dae46d4f4380d86f
Best match: aiohttp 4.0.0a1
Processing aiohttp-4.0.0a1.tar.gz
Writing /tmp/easy_install-ft85y_rb/aiohttp-4.0.0a1/setup.cfg
Running aiohttp-4.0.0a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ft85y_rb/aiohttp-4.0.0a1/egg-dist-tmp-psu71vk7
**********************
* Accellerated build *
**********************
warning: no files found matching 'aiohttp' anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.lib' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.obj' found anywhere in distribution
warning: no previously-included files found matching 'aiohttp/*.html'
no previously-included directories found matching 'docs/_build'

unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 62, in fetch_build_egg
    pkg_resources.get_distribution('pip')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/usr/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.8/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/usr/lib/python3.8/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ft85y_rb/aiohttp-4.0.0a1/setup.py", line 124, in <module>
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ft85y_rb/aiohttp-4.0.0a1/setup.py", line 124, in <module>
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 718, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 781, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 70, in fetch_build_egg
    return _legacy_fetch_build_egg(dist, req)
  File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 53, in _legacy_fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 712, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 923, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1191, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1179, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
ubuntu@ip-172-31-63-193:~/buster$
ubuntu@ip-172-31-63-193:~/buster$
ubuntu@ip-172-31-63-193:~/buster$ ls
LICENSE  README.md  buster  buster-demo.gif  data  setup.py
ubuntu@ip-172-31-63-193:~/buster$ cd buster/
ubuntu@ip-172-31-63-193:~/buster/buster$ ls
__init__.py  __main__.py  lib
ubuntu@ip-172-31-63-193:~/buster/buster$ cd ..
ubuntu@ip-172-31-63-193:~/buster$
ubuntu@ip-172-31-63-193:~/buster$
ubuntu@ip-172-31-63-193:~/buster$
ubuntu@ip-172-31-63-193:~/buster$ buster -h

Command 'buster' not found, did you mean:

  command 'busted' from deb lua-busted (2.0.0-1)

Try: sudo apt install <deb name>

**Comment by haarshdev** [comment]
Hi again,

I was able to resolve the issue after installing pip using the below command

sudo apt install python3-pip

I ran 'sudo python3 setup.py install' after installing pip and it worked!

Didn't delete the issue since I hope it will help someone else with this issue.

Thanks
