### ISSUE TITLE
install does not work

### ISSUE THREAD

**Issue by ghost** [sham00n/buster#34]
i tried installing and i got this massive mess:

WARNING: The wheel package is not available.
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-97whrtw9/twint_be54099f01cd4cb0b94b10001b4593e3/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-97whrtw9/twint_be54099f01cd4cb0b94b10001b4593e3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ktx1fu3l
       cwd: /tmp/pip-wheel-97whrtw9/twint_be54099f01cd4cb0b94b10001b4593e3/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for twint
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpdsu0mqdx', '--quiet', 'twint']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yourfutureboyfriend/Downloads/buster/setup.py", line 16, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpdsu0mqdx', '--quiet', 'twint']' returned non-zero exit status 1.

i notice that this repo has multiple open issues and the dev has not done anything since 2019. is this repo dead at this point?

**Comment by ibexdata** [comment]
I was having setup issues related to building the cchardet extension ("implicit-function-declaration is not valid for C++").

While I manually installed cchardet and cython, I then received permission issues running setup.py. Installing using `sudo` helped, but the warnings are clear: _**"Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager."**_ 

Consider yourself double-warned.

```
sudo pip install cython
sudo pip install cchardet
sudo python3 setup.py install
```
