### ISSUE TITLE
Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by aliraza78** [sham00n/buster#4]
These error messages are cropping up while installation.

/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'
  warnings.warn(msg)
warning: no files found matching 'changelog.rst'
warning: no files found matching 'Makefile.ext'
warning: no files found matching 'known_failures.py'
warning: no files found matching '.pep8'
no previously-included directories found matching '*/__pycache__'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.lo' found anywhere in distribution
warning: no previously-included files matching '*.la' found anywhere in distribution
warning: no previously-included files matching '.dirstamp' found anywhere in distribution
warning: no previously-included files matching 'config.log' found anywhere in distribution
warning: no previously-included files matching 'config.status' found anywhere in distribution
warning: no previously-included files matching 'config.cache' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.coverage' found under directory 'src/greentest'
no previously-included directories found matching 'src/greentest/htmlcov'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/c-ares'
warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps/c-ares'
warning: no previously-included files matching '_corecffi.c' found under directory 'src/gevent'
warning: no previously-included files found matching 'configure-output'
warning: no previously-included files found matching 'configure-output.txt'
warning: no previously-included files found matching 'deps/TAGS'
warning: no previously-included files found matching 'deps/c-ares/ares_build.h'
warning: no previously-included files found matching 'deps/c-ares/ares_config.h'
warning: no previously-included files found matching 'deps/c-ares/libcares.pc'
warning: no previously-included files found matching 'deps/c-ares/libtool'
warning: no previously-included files found matching 'deps/c-ares/Makefile'
no previously-included directories found matching 'deps/c-ares/.deps'
no previously-included directories found matching 'deps/c-ares/.libs'
no previously-included directories found matching 'deps/libev/.deps'
no previously-included directories found matching 'deps/libev/.libs'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libev'
warning: no previously-included files matching 'libtool' found under directory 'deps/libev'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/libev'
warning: no previously-included files matching 'config.h' found under directory 'deps/libev'
no previously-included directories found matching 'deps/libuv/.deps'
no previously-included directories found matching 'deps/libuv/.libs'
no previously-included directories found matching 'deps/libuv/src/.deps'
no previously-included directories found matching 'deps/libuv/src/unix/.deps'
no previously-included directories found matching 'deps/libuv/src/win/.deps'
no previously-included directories found matching 'deps/libuv/test/.deps'
no previously-included directories found matching 'deps/libuv/autom4te.cache'
no previously-included directories found matching 'deps/libuv/m4'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libuv'
warning: no previously-included files matching 'Makefile.in' found under directory 'deps/libuv'
warning: no previously-included files matching 'ar-lib' found under directory 'deps/libuv'
warning: no previously-included files matching 'aclocal.m4' found under directory 'deps/libuv'
warning: no previously-included files matching 'compile' found under directory 'deps/libuv'
warning: no previously-included files matching 'configure' found under directory 'deps/libuv'
warning: no previously-included files matching 'depcomp' found under directory 'deps/libuv'
warning: no previously-included files matching 'install-sh' found under directory 'deps/libuv'
warning: no previously-included files matching 'libtool' found under directory 'deps/libuv'
warning: no previously-included files matching 'libuv.pc' found under directory 'deps/libuv'
warning: no previously-included files matching 'ltmain.sh' found under directory 'deps/libuv'
warning: no previously-included files matching 'missing' found under directory 'deps/libuv'
Running '(cd  "/tmp/easy_install-sfa71w6u/gevent-1.5a1/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/easy_install-sfa71w6u/gevent-1.5a1
Embedding c-ares <_setuputils.ConfiguringBuildExt object at 0x7f189bfcd5f8> <_setuputils.Extension('gevent.resolver.cares') at 0x7f189bff6c50>
Inserted  build/temp.linux-x86_64-3.7/c-ares in include dirs ['build/temp.linux-x86_64-3.7/c-ares', 'src/gevent/resolver', '/tmp/easy_install-sfa71w6u/gevent-1.5a1/deps/c-ares']
Running '(cd  "/tmp/easy_install-sfa71w6u/gevent-1.5a1/deps/c-ares"  && if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   && sh ./configure --disable-dependency-tracking -C CONFIG_COMMANDS=   && cp ares_config.h ares_build.h "$OLDPWD"   && cat ares_build.h   && if [ -r ares_build.h.orig ]; then mv ares_build.h.orig ares_build.h; fi) > configure-output.txt' in /tmp/easy_install-sfa71w6u/gevent-1.5a1/build/temp.linux-x86_64-3.7/c-ares
x86_64-linux-gnu-gcc: error: src/gevent/_greenlet_primitives.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_hub_primitives.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_hub_local.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_waiter.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/greenlet.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_tracer.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_abstract_linkable.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_semaphore.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/local.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_ident.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/_imap.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/event.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/queue.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc: error: src/gevent/libev/corecext.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_parallel()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 469, in _build_extensions_parallel
    fut.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/easy_install-sfa71w6u/gevent-1.5a1/_setuputils.py", line 266, in build_extension
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sfa71w6u/gevent-1.5a1/setup.py", line 420, in <module>
  File "/tmp/easy_install-sfa71w6u/gevent-1.5a1/setup.py", line 404, in run_setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sfa71w6u/gevent-1.5a1/setup.py", line 420, in <module>
  File "/tmp/easy_install-sfa71w6u/gevent-1.5a1/setup.py", line 404, in run_setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    package_data={'data': ['email-providers.json','api-keys.yaml','domain_list.json']},
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1171, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by sham00n** [comment]
duplicate issue of #1
